In [5]:
import pandas as pd
import os
import json

In [24]:

file = '../ecobici_lista_stations.json'

json_data = pd.read_json('../ecobici_lista_stations.json')

json_data

# stations_colonias = json_data['stations']

                                              stations
0    {'id': 124, 'name': '124 CLAUDIO BERNARD-DR. L...
1    {'id': 159, 'name': '159 HUATABAMPO-EJE 1 PTE....
2    {'id': 241, 'name': 'E241 EJERCITO NAL-JUAN VA...
3    {'id': 243, 'name': '243 MIGUEL DE CERVANTES S...
4    {'id': 350, 'name': '350 JOSE CLEMENTE OROZCO-...
..                                                 ...
475  {'id': 380, 'name': '380 MORAS-SAN LORENZO', '...
476  {'id': 440, 'name': '440 REAL DE MAYORAZGO-PUE...
477  {'id': 441, 'name': '441 PUENTE XOCO-REAL DE M...
478  {'id': 442, 'name': '442 REAL DE MAYORAZGO-AVE...
479  {'id': 426, 'name': '426 CERRADA DE POPOCATEPE...

[480 rows x 1 columns]

In [27]:
unpack = json_data.stations.dropna().apply(pd.Series)
unpack

,id,name,address,addressNumber,zipCode,districtCode,districtName,altitude,nearbyStations,location,stationType
0,124,124 CLAUDIO BERNARD-DR. LICEAGA,124 - Claudio Bernard-Dr. Liceaga,S/N,06500,1,Ampliación Granada,None,"[119, 123, 133]","{'lat': 19.422392, 'lon': -99.150358}",BIKE
1,159,159 HUATABAMPO-EJE 1 PTE. AV. CUAUHTÉMOC,159 - Huatabampo-Eje 1 Pte. Av. Cuauhtémoc,S/N,06760,1,Ampliación Granada,None,"[155, 158, 163]","{'lat': 19.407517, 'lon': -99.155373}",BIKE
2,241,E241 EJERCITO NAL-JUAN VAZQUEZ DE LA MELLA,241 - Ejercito Nacional-Juan Vazquez de la Mella,S/N,11520,1,Ampliación Granada,None,"[222, 460]","{'lat': 19.43862, 'lon': -99.20758}",ELECTRIC_BIKE
3,243,243 MIGUEL DE CERVANTES SAAVEDRA-LAGO FILT,243 - Miguel de Cervantes Saavedra-Lago Filt,S/N,11510,1,Ampliación Granada,None,"[199, 242, 244]","{'lat': 19.440839, 'lon': -99.196712}",BIKE
4,350,350 JOSE CLEMENTE OROZCO-CORREGGIO,350 - Jose Clemente Orozco-Correggio,S/N,3710,1,Ampliación Granada,None,"[349, 352]","{'lat': 19.384062, 'lon': -99.181482}",BIKE
...,...,...,...,...,...,...,...,...,...,...,...
475,380,380 MORAS-SAN LORENZO,380 - Moras-San Lorenzo,S/N,3200,TLA,Tlacoquemecatl,None,"[392, 393, 394]","{'lat': 19.374876, 'lon': -99.173512}",BIKE
476,440,440 REAL DE MAYORAZGO-PUENTE XOCO,440 - Real De Mayorazgo-Puente Xoco,S/N,3330,XOC,Xoco,None,"[433, 439, 441]","{'lat': 19.36065, 'lon': -99.168669}",BIKE
477,441,441 PUENTE XOCO-REAL DE MAYORAZGO,441 - Puente Xoco-Real De Mayorazgo,S/N,3330,XOC,Xoco,None,"[433, 442]","{'lat': 19.361215, 'lon': -99.167527}",BIKE
478,442,442 REAL DE MAYORAZGO-AVENIDA MÉXICO-COYOACAN,442 - Real De Mayorazgo-Avenida México-Coyoacan,S/N,3330,XOC,Xoco,None,"[432, 443, 444]","{'lat': 19.359905, 'lon': -99.1653}","BIKE,TPV"
479,426,426 CERRADA DE POPOCATEPETL-AV. POPOCATEPETL E...,426 - Cerrada De Popocatepetl-Av. Popocatepetl...,S/N,3330,XOC,Xoco,None,"[411, 412, 425]","{'lat': 19.365519, 'lon': -99.166017}",BIKE

In [38]:
unique_colonias = pd.DataFrame(unpack['districtName'].unique())
print(f'Unique Colonias: {len(unique_colonias)}')
unique_colonias

Unique Colonias: 49

                                   0
0                 Ampliación Granada
1                            Anzures
2                            Acacias
3                            Actipan
4           Anáhuac Mariano Escobedo
5                 Ampliación Nápoles
6                  Anáhuac Dos Lagos
7                          Anáhuac I
8                         Buenavista
9             Ciudad de los Deportes
10                            Centro
11             Bosque de Chapultepec
12                           Condesa
13                        Cuauhtémoc
14                 Cuauhtémoc Pensil
15                          Doctores
16                  Del Valle Centro
17                   Del Valle Norte
18                     Del Valle Sur
19                          Escandón
20           Extremadura Insurgentes
21         General Pedro Maria Anaya
22                           Granada
23                 Hipódromo Condesa
24                         Hipódromo
25               Insurgentes Mixcoac
26                        Irrigación
27             Insurgentes San Borja
28                            Juárez
29    Lomas de Chapultepec Sección V
30  Lomas de Chapultepec Sección III
31                      Letran Valle
32                    Molino del Rey
33                           Nápoles
34                 Narvarte Poniente
35                       Noche Buena
36                   Piedad Narvarte
37                           Polanco
38           Residencial Emperadores
39                        Roma Norte
40                          Roma Sur
41                 Santa Cruz Atoyac
42           San Miguel Chapultepec
43              Santa María Nonoalco
44            San Pedro de los Pinos
45                        San Rafael
46                        Tabacalera
47                    Tlacoquemecatl
48                              Xoco