In [10]:
# Dependencies

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import glob
import os
from scipy import stats
import timeit                                # To check performance

## Note: 

The unified CSV file is nearly 5GBs. Github can't store it. If you try to push it, it will produce an error. 

If you want to work with the data, you can run this script, and it will save the unified CSV file in the sub folder "Gitignore-data-output-files."

HOWEVER, BEFORE doing that, open your .gitignore file in the repository, and make sure the following is one of the line items to ignore:

"# Huge data files to ignore:
Resources/Data/Gitignore-data-output-files/ecobici_ride_data-unified.csv"

Save your .gitignore file, push that change. Then you should be able to produce the unified CSV file without worry of your machine trying to push it to the repository. -Ken

In [11]:
# Concatenate csv files

tic = timeit.default_timer()                            # Monitor performance

path = r'/Users/kennethandersen/Documents/GitHub/P2-Ecobici_insights_and_recommendations/Resources/Data'
all_files = glob.glob(path + "/*.csv")

csv_file_list = []
i = 1

for filename in all_files:
    try:
        df = pd.read_csv(filename, index_col=None, header=0)
        csv_file_list.append(df)
#         print (f'File {i} added')
    except:
        print(f'Error {filename}, could not be added')
        pass
    i+= 1

ecobici_rides_df = pd.concat(csv_file_list, axis=0, ignore_index=True)

toc = timeit.default_timer()                            # Monitor performance
print(f'Time (in seconds) to extract and concatenate excel files: {round(toc - tic, 2)}')
print(f'Number of rows: {len(ecobici_rides_df)}')

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

Error /Users/kennethandersen/Documents/GitHub/P2-Ecobici_insights_and_recommendations/Resources/Data/2020-12.csv, could not be added

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (2,6,9) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

Time (in seconds) to extract and concatenate excel files: 94.98
Number of rows: 71070670

In [12]:
ecobici_rides_df

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_Estacion_Arribo,Fecha_Arribo,Hora_Arribo,Ciclo_EstacionArribo,Fecha Arribo,Hora Arribo,Hora_Retiro.1,Unnamed: 9,BikeID
0,M,44.0,4357,442.0,01/02/2020,0:00:38,116,01/02/2020,0:35:17,NaN,NaN,NaN,NaN,NaN,NaN
1,M,22.0,12083,66.0,01/02/2020,0:00:53,37,01/02/2020,0:06:23,NaN,NaN,NaN,NaN,NaN,NaN
2,M,29.0,11562,331.0,01/02/2020,0:00:55,341,01/02/2020,0:26:47,NaN,NaN,NaN,NaN,NaN,NaN
3,M,27.0,10206,164.0,01/02/2020,0:01:18,35,01/02/2020,0:16:51,NaN,NaN,NaN,NaN,NaN,NaN
4,M,27.0,10101,120.0,01/02/2020,0:01:18,47,01/02/2020,0:12:39,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71070665,M,25.0,474,12.0,2011-07-30,23:44:04.383000,20,2011-07-31,01:42:19.887000,NaN,NaN,NaN,NaN,NaN,NaN
71070666,F,37.0,476,76.0,2011-07-30,23:55:36.703000,64,2011-07-31,00:01:11.147000,NaN,NaN,NaN,NaN,NaN,NaN
71070667,M,25.0,491,48.0,2011-07-30,23:56:50.237000,26,2011-07-31,00:01:42.333000,NaN,NaN,NaN,NaN,NaN,NaN
71070668,M,31.0,868,76.0,2011-07-30,23:56:51.347000,64,2011-07-31,00:01:19.100000,NaN,NaN,NaN,NaN,NaN,NaN
71070669,F,23.0,285,81.0,2011-07-30,23:57:47.830000,63,2011-07-31,00:02:29.600000,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Export unified CSV file to master CSV file

tic = timeit.default_timer()                            # Monitor performance

ecobici_rides_df.to_csv("Gitignore-data-output-files/ecobici_ride_data-unified.csv", index=False) 

toc = timeit.default_timer()                            # Monitor performance
print(f'Time (in seconds) to extract excel sheet: {round(toc - tic, 2)}')

Time (in seconds) to extract excel sheet: 312.7